program: train.py
name :  Sweep_ResNet # sweep run name!!
method: bayes # bayes, grid
metric:
    name: testAMC_F1_Class1Raw
    goal: maximize
parameters:
    # dataSeed:
    #     values: [0,1,2,3,4,5,6,7,8]
    modelName:
        values: ['efficientnet-b0','resnet34'] #'U2NET', 'U2NETP', 'resnet34','resnet50', 'efficientnet-b0', 'efficientnet-b1','efficientnet-b2'
    # norm:
    #     values: ['instance','group','layer','batch']
    # featureLength:
    #     values: [1024, 1280]
    # dataNorm:
    #     values: ['zscoreI', 'zscoreO', 'minmaxI']
    # sampler:
    #     values: [True, False]
    # lossFn:
    #     values: ['BCE', 'FOCAL', 'BCEFOCAL']
    # outChannels:
    #     values: [2,3,4]
    upsample:
        values: ['deconv', 'pixelshuffle','nontrainable']
    supervision: 
        values: ['TYPE1','TYPE2']
    # trainaug:
    #     values: ['NONE', 'NEUROKIT2']
    # encModule:
    #     values: ['ACM', 'SE', 'MHA', 'NONE'] # 'SE', 'DEEPRFT', 'ACM', 'MHA', 
    decModule:
        values: ['ACM', 'SE', 'MHA', 'NONE'] # 'SE', 'DEEPRFT', 'NLNN', 'CBAM',
    segheadModule:
        values: ['SE', 'MHA', 'NONE']
    mtl:
        values: ['CLS', 'REC', 'ALL_max', 'ALL_avg', 'NONE']