program: train.py
name :  Sweep_ResNet # sweep run name!!
method: grid # bayes, grid
metric:
    name: testAMC_F1_Class1Raw
    goal: maximize
parameters:
    # dataSeed:
    #     values: [0,1,2,3,4,5,6,7,8]
    modelName:
        values: ['resnet34','efficientnet-b0'] #'U2NET', 'U2NETP', 'resnet34','resnet50', 'efficientnet-b0', 'efficientnet-b1','efficientnet-b2'
    # norm:
    #     values: ['instance','group','layer','batch']
    # featureLength:
    #     values: [1024, 1280]
    # dataNorm:
    #     values: ['zscoreI', 'zscoreO', 'minmaxI']
    # sampler:
    #     values: [True, False]
    # lossFn:
    #     values: ['BCE', 'FOCAL', 'BCEFOCAL']
    # outChannels:
    #     values: [2,3,4]
    # upsample:
    #     values: ['deconv', 'pixelshuffle']
    # supervision: 
    #     values: ['TYPE2'] # 'TYPE1', 'NONE'
    # trainaug:
    #     values: ['NONE', 'NEUROKIT2']
    # encModule:  
    #     values: ['NONE', 'ACM', 'CBAM', 'DEEPRFT', 'FFC', 'MHA', 'NLNN', 'SE'] # 'SE', 'DEEPRFT', 'ACM', 'MHA',  
    encModule:  
        values: ['SCM1', 'SCM2', 'SCM3', 'SCM4', 'NONE'] # 'SE', 'DEEPRFT', 'ACM', 'MHA',      # encModule:
    #     values: ['none', 'acm', 'cbam', 'deeprft', 'ffc', 'nlnn', 'se'] # 'none', 'acm', 'cbam', 'deeprft', 'ffc', 'nlnn','se' 
    # decModule:
    #     values: ['NONE', 'ACM', 'CBAM', 'MHA', 'NLNN', 'SE'] # 'NONE', 'ACM', 'CBAM', 'DEEPRFT', 'FFC', 'MHA', 'NLNN', 'SE']
    # segheadModule:
    #     values: ['MHA', 'NONE']
    # mtl:
    #     values: ['NONE'] # 'CLS', 'REC', 'ALL_max', 'ALL_avg', 