program: train.py
name :  20230206_test # sweep run name!!
method: bayes
metric:
    name: testMIT_AUPRC_Class1Raw
    goal: maximize
parameters:
    modelName:
        values: ['efficientnet-b0','efficientnet-b1','efficientnet-b2']
    norm:
        values: ['instance','group','layer','batch']
    # featureLength:
    #     values: [1024, 1280]
    dataNorm:
        values: ['zscore_i', 'zscore_o', 'minmax_i']
    se_module:
        values: ['se','acm','nlnn','deeprft','cbam']
    lossFn:
        values: ['bceloss','dicebceloss']
    upsample:
        values: ['deconv', 'pixelshuffle']
    supervision: 
        values: ['NONE','TYPE1','TYPE2']
    trainaug:
        values: ['NEUROKIT2']
    skipModule:
        values: ['NONE', 'DEEPRFT_BOTTOM5', 'ACM4_0_BOTTOM5', 'MHA_BOTTOM5']
    segheadModule:
        values: ['NONE','SE']